# Copyright (c) 2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# -----------------------------------------------------------------------------
# Recommended: set up configuration validation, see https://bit.ly/3WT2GkR
# -----------------------------------------------------------------------------

# Project information
site_name: Example
# site_url: https://example.com/
site_author: Martin Donath
site_description: >-
  This project lists all options that are supported by Material for MkDocs
  and can be used as a basis for new projects or reproductions.

# Repository
repo_name: mkdocs-material/examples
repo_url: https://github.com/mkdocs-material/examples
# edit_uri: edit/master/docs/

# Copyright
copyright: Copyright &copy; 2022 Martin Donath

# Directories
# docs_dir: docs
# site_dir: site
# use_directory_urls: false

# Runtime
# strict: true
# dev_addr: 127.0.0.1:8000

# Deployment
# remote_branch: gh-pages
# remote_name: origin

# Extra assets
# extra_css: [extra.css]
# extra_javascript: [extra.js]

# Theme
theme:
  name: material
  # custom_dir: overrides
  # static_templates:
  #   - 404.html

  # Language and directionality
  language: en
  # direction: ltr

  # Favicon and logo
  # favicon: path/to/file.png
  # logo: path/to/file.png

  # Icons
  icon:
    # edit: material/pencil
    logo: material/library
    # repo: fontawesome/brands/git-alt
    # admonition:
    #   note: material/pencil
    #   abstract: material/clipboard-text
    #   info: material/information
    #   tip: material/fire
    #   success: material/check-bold
    #   question: material/help-circle
    #   warning: material/alert
    #   failure: material/close
    #   danger: material/lightning-bolt-circle
    #   bug: material/shield-bug
    #   example: material/test-tube
    #   quote: material/format-quote-close

  # Feature flags
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.code.copy
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate

  # Color palette
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Google Fonts
  # font:
  #   text: Roboto
  #   code: Roboto Mono

# Plugins
plugins:

  # Built-in plugin: blog
  # - blog:
  #     enabled: true
  #     blog_dir: blog
  #     post_date_format: long
  #     post_url_date_format: yyyy/MM/dd
  #     post_url_format: "{date}/{slug}"
  #     post_excerpt: optional
  #     post_excerpt_separator: <!-- more -->
  #     post_excerpt_max_authors: 1
  #     post_excerpt_max_categories: 5
  #     post_readtime: true
  #     post_readtime_words_per_minute: 265
  #     archive: true
  #     archive_name: Archive
  #     archive_date_format: yyyy
  #     archive_url_date_format: yyyy
  #     archive_url_format: "archive/{date}"
  #     categories: true
  #     categories_name: Categories
  #     categories_url_format: "category/{slug}"
  #     categories_allowed: []
  #     pagination: true
  #     pagination_per_page: 10
  #     pagination_url_format: "page/{page}"
  #     pagination_template: ~2~
  #     pagination_keep_content: false
  #     authors: true
  #     authors_file: .authors.yml
  #     draft: true
  #     draft_on_serve: true
  #     draft_if_future_date: false

  # Built-in plugin: meta
  # - meta:
  #     meta_file: "**/.meta.yml"

  # Built-in plugin: offline
  # - offline:
  #     enabled: true

  # Built-in plugin: privacy
  # - privacy:
  #     enabled: true
  #     external_assets: bundle
  #     external_assets_dir: assets/external
  #     external_links: true
  #     external_links_attr_map: {}
  #     external_links_noopener: true

  # Built-in plugin: search
  - search:
      lang: en
      separator: '[\s-]+'

  # Built-in plugin: social
  # - social:
  #     cards: true
  #     cards_dir: assets/images/social
  #     cards_font: Roboto
  #     cards_color:
  #       fill: black
  #       text: white

  # Built-in plugin: tags
  # - tags:
  #     enabled: true
  #     tags_file: tags.md
  #     tags_extra_files: {}
  #     tags_allowed: []

  # Plugin: mkdocs-git-committers-plugin-2
  # - git-committers:
  #     enabled: true
  #     repository: mkdocs-material/examples
  #     branch: master

  # Plugin: mkdocs-git-revision-date-localized-plugin
  # - git-revision-date-localized:
  #     enabled: true
  #     type: date
  #     exclude: []
  #     fallback_to_build_date: false
  #     enable_creation_date: false

  # Plugin: mkdocs-glightbox
  # - glightbox:
  #     touchNavigation: true
  #     loop: false
  #     effect: zoom
  #     width: "100%"
  #     height: auto
  #     zoomable: true
  #     draggable: true
  #     auto_caption: false
  #     caption_position: bottom

  # Plugin: mkdocs-minify-plugin
  # - minify:
  #     minify_html: true

  # Plugin: mkdocs-redirects
  # - redirects:
  #     redirect_maps:
  #       old.md: new.md

  # Plugin: mkdocs-rss-plugin
  # - rss:
  #     enabled: true
  #     abstract_chars_count: 160
  #     feed_ttl: 1440
  #     length: 20
  #     match_path: .*
  #     pretty_print: false

# Extra configuration
extra:

  # Site analytics
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    # feedback:
    #   title: Was this page helpful
    #   ratings:
    #     - icon: material/emoticon-happy-outline
    #       name: This page was helpful
    #       data: 1
    #       note: Thanks for your feedback!
    #     - icon: material/emoticon-sad-outline
    #       name: This page could be improved
    #       data: 0
    #       note: Thanks for your feedback!

  # Cookie consent
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as
  #     well as to measure the effectiveness of our documentation and whether
  #     users find what they're searching for. With your consent, you're
  #     helping us to make our documentation better.
  #   actions:
  #     - accept
  #     - manage

  # Social links
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/squidfunk
  #   - icon: fontawesome/brands/gitter
  #     link: https://gitter.im/squidfunk/mkdocs-material
  #   - icon: fontawesome/brands/docker
  #     link: https://hub.docker.com/r/squidfunk/mkdocs-material/
  #   - icon: fontawesome/brands/python
  #     link: https://pypi.org/project/mkdocs-material/
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/squidfunk

  # Site language selector
  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: Deutsch
  #     link: /de/
  #     lang: de

  # Tag identifiers
  # tags: {}

  # Versioning
  # version:
  #   provider: mike

  # Generator notice
  # generator: true

# Markdown extensions
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: mkdocs-material
      repo: examples
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
